import React, { useCallback, useMemo, useState } from 'react';
import { router } from 'expo-router';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { ArrowLeft, ChevronDown, ChevronRight } from 'lucide-react-native';
import {
  PRISMHeader,
  PRISMIconButton,
  fontWeight,
  radius,
  spacing,
  type,
  useTheme,
} from '@prism/ui';

interface Acknowledgement {
  name: string;
  version: string;
  license: string;
  copyright: string[];
  /** Index into `bodies`, or null when the package ships no license file. */
  body: number | null;
}

interface AcknowledgementsFile {
  packages: Acknowledgement[];
  bodies: string[];
}

/** Generated by scripts/generate-acknowledgements.mjs; loaded only when this screen opens. */
function loadAcknowledgements(): AcknowledgementsFile {
  return require('../../../assets/acknowledgements.json') as AcknowledgementsFile;
}

/** Open-source software in Prism, with each package's copyright and license. Tap one to read it. */
export function AcknowledgementsScreen() {
  const theme = useTheme();
  const data = useMemo(loadAcknowledgements, []);
  const [open, setOpen] = useState<string | null>(null);

  const renderItem = useCallback(
    ({ item }: { item: Acknowledgement }) => {
      const key = `${item.name}@${item.version}`;
      const expanded = open === key;
      const Chevron = expanded ? ChevronDown : ChevronRight;
      return (
        <View style={[styles.item, { borderBottomColor: theme.colors.border.subtle }]}>
          <Pressable
            accessibilityRole="button"
            accessibilityState={{ expanded }}
            accessibilityLabel={`${item.name}, ${item.license}`}
            onPress={() => setOpen(expanded ? null : key)}
            style={styles.row}
          >
            <View style={styles.rowText}>
              <Text style={[styles.name, { color: theme.colors.text.primary }]}>{item.name}</Text>
              <Text style={[styles.meta, { color: theme.colors.text.tertiary }]}>
                {item.version} · {item.license}
              </Text>
            </View>
            <Chevron size={18} color={theme.colors.text.tertiary} />
          </Pressable>
          {expanded ? (
            <View style={[styles.license, { backgroundColor: theme.colors.surfaceElevated }]}>
              {item.copyright.map((line, index) => (
                <Text
                  key={index}
                  style={[styles.licenseText, { color: theme.colors.text.primary }]}
                >
                  {line}
                </Text>
              ))}
              <Text style={[styles.licenseText, { color: theme.colors.text.secondary }]}>
                {item.body === null
                  ? `Licensed under ${item.license}.`
                  : (data.bodies.at(item.body) ?? '')}
              </Text>
            </View>
          ) : null}
        </View>
      );
    },
    [open, data, theme],
  );

  return (
    <View style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <PRISMHeader
        title="Acknowledgements."
        leading={
          <PRISMIconButton accessibilityLabel="Back" onPress={() => router.back()}>
            <ArrowLeft size={22} color={theme.colors.text.primary} />
          </PRISMIconButton>
        }
      />
      <FlatList
        data={data.packages}
        keyExtractor={(item) => `${item.name}@${item.version}`}
        renderItem={renderItem}
        extraData={open}
        initialNumToRender={20}
        contentContainerStyle={styles.content}
        ListHeaderComponent={
          <Text style={[styles.intro, { color: theme.colors.text.secondary }]}>
            Prism is built with open-source software. Thank you to everyone who made these{' '}
            {data.packages.length} packages.
          </Text>
        }
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  intro: {
    fontSize: type.bodyM.fontSize,
    lineHeight: type.bodyM.lineHeight,
    marginBottom: spacing.md,
  },
  item: {
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 52,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  rowText: {
    flex: 1,
  },
  name: {
    fontSize: type.bodyM.fontSize,
    lineHeight: type.bodyM.lineHeight,
    fontWeight: fontWeight.semibold as '600',
  },
  meta: {
    fontSize: type.bodyS.fontSize,
    lineHeight: type.bodyS.lineHeight,
  },
  license: {
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.md,
    gap: spacing.xs,
  },
  licenseText: {
    fontSize: type.bodyS.fontSize,
    lineHeight: type.bodyS.lineHeight,
  },
});
